replicaCount: 1

image:
  repository: mahmoudemmad/tfgrid-stats
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: omda.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

  # For traefik 
  # annotations:
  #   kubernetes.io/ingress.class: traefik
  #   ingress.kubernetes.io/ssl-passthrough: "true"
  #   traefik.ingress.kubernetes.io/router.tls.certresolver: gridca

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 900m
    memory: 1000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
